### ISSUE TITLE
Please add link to metadata

### ISSUE THREAD

**Issue by pcav** [csandor/polygonsplitter#1]
Link to this repo is ok.
Thanks.

**Comment by csandor** [comment]
Add link where pointing to where? :) Thx.

**Comment by pcav** [comment]
to this it would be OK:
https://github.com/csandor/polygonsplitter/

**Comment by csandor** [comment]
It's actually there:
Plugin home page https://github.com/csandor/polygonsplitter/

**Comment by csandor** [comment]
Among details

**Comment by pcav** [comment]
but not in the repo field. sorry for bothering, I'm trying to have all the necessary metadata clean.

**Comment by csandor** [comment]
Nopb. thanks for notifying!
This is in metadata:
homepage=https://github.com/csandor/polygonsplitter/
tracker=https://github.com/csandor/polygonsplitter/issues
repository=https://github.com/csandor/polygonsplitter.git

Shall I change the repo field to be === homepage?

**Comment by pcav** [comment]
Now it's OK, thanks
